// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("calendar.caldav.googleResync", 1762999476);
user_pref("calendar.list.sortOrder", "39cbd1f0-2f3b-435b-83bc-cf09877b05ed");
user_pref("calendar.registry.39cbd1f0-2f3b-435b-83bc-cf09877b05ed.calendar-main-default", true);
user_pref("calendar.registry.39cbd1f0-2f3b-435b-83bc-cf09877b05ed.calendar-main-in-composite", true);
user_pref("calendar.registry.39cbd1f0-2f3b-435b-83bc-cf09877b05ed.disabled", true);
user_pref("calendar.registry.39cbd1f0-2f3b-435b-83bc-cf09877b05ed.name", "Home");
user_pref("calendar.registry.39cbd1f0-2f3b-435b-83bc-cf09877b05ed.type", "storage");
user_pref("calendar.registry.39cbd1f0-2f3b-435b-83bc-cf09877b05ed.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "UTC");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("calendar.ui.version", 3);
user_pref("datareporting.dau.cachedUsageProfileGroupID", "a4ecb010-8cc9-4379-817b-712229af8d4b");
user_pref("datareporting.dau.cachedUsageProfileID", "3aa19423-88cb-42c5-b9c3-98310d371ad6");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1762999486946");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.hasExperimentsInstalled", false);
user_pref("extensions.hasExtensionsInstalled", false);
user_pref("extensions.installedDistroAddon.langpack-en-US@thunderbird.mozilla.org", true);
user_pref("extensions.lastAppBuildId", "20250917073259");
user_pref("extensions.lastAppVersion", "140.3.0");
user_pref("extensions.lastPlatformVersion", "140.3.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"a429f27e-0454-45e2-aca3-2e7bba938c10\"}");
user_pref("mail.ui-rdf.version", 51);
user_pref("mailnews.database.global.datastore.id", "7492ee71-36fb-4977-a624-4b58ae41616");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.start_page_override.mstone", "140.3.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("toolkit.startup.last_success", 1762999460);
user_pref("toolkit.telemetry.cachedClientID", "c73b68d3-fdc6-4734-a428-966c9219036a");
user_pref("toolkit.telemetry.cachedProfileGroupID", "3dba1274-1c15-4c6b-aa01-1b502b449847");
user_pref("toolkit.telemetry.previousBuildID", "20250917073259");
